# Generated by Django 5.0.4 on 2024-05-02 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_of_transaction', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='pending_transaction', max_length=10)),
                ('transaction_date_time', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('receiving_money_from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiving_money_from_user', to=settings.AUTH_USER_MODEL)),
                ('transfering_money_to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfering_money_to_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
